version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    environment:
      UPSTREAM1: 'https://9.9.9.9/dns-query'
      UPSTREAM2: 'https://149.112.112.112/dns-query'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports: 
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    environment:
      WEBPASSWORD: 'dnsoverhttps'
      DNS1: '10.0.0.2#5054'
      DNS2: '10.0.0.2#5053'
      TZ: 'Etc/UTC'
      DNSMASQ_LISTENING: 'all'
      IPv6: 'false'
    dns:
      - 127.0.0.1
      - 9.9.9.9
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
