version: "3.5"

services:
  unbound:
    container_name: unbound
    hostname: unbound
    image: klutchell/unbound
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.5.11.2

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports: 
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "10443:443/tcp"
    networks:
      pihole_net:
        ipv4_address: 10.5.11.3
    environment:
      WEBPASSWORD: 'CHANGEME'
      TZ: 'UTC'
      WEBTHEME: 'default-dark'
      WEBUIBOXEDLAYOUT: 'traditional'
      PIHOLE_DNS_: '10.5.11.2;10.5.11.2'
      DNSMASQ_USER: 'pihole'
      DNSMASQ_LISTENING: 'all'
      DNSSEC: 'true'
      IPv6: 'false'
    volumes:
     - type: volume
       source: pihole_etc
       target: /etc/pihole/
     - type: volume
       source: pihole_dnsmasq
       target: /etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 9.9.9.9
    cap_add:
      - NET_ADMIN

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true

volumes:
  pihole_etc:
  pihole_dnsmasq:

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.11.0/29
