# version: '3.8'
services:
  orbit:
    image: ghcr.io/orbitscanner/orbit:latest
    ports:
      - "8090:8090"
    environment:
      - API_ENCRYPTION_KEY=12345678901234567890123456789012
    volumes:
      - orbit_data:/data
    restart: unless-stopped

volumes:
  orbit_data:
