version: "3.5"

services:
  cloudflared:
    container_name: cloudflared
    hostname: cloudflared
    image: crazymax/cloudflared:latest
    restart: unless-stopped
    environment:
      - "TZ=UTC"
      - "TUNNEL_DNS_UPSTREAM=https://9.9.9.9/dns-query,https://149.112.112.112/dns-query"
    networks:
      pihole_net:
        ipv4_address: 10.5.11.2

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports: 
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      pihole_net:
        ipv4_address: 10.5.11.3
    environment:
      WEBPASSWORD: 'CHANGEME'
      TZ: 'UTC'
      WEBTHEME: 'default-dark'
      WEBUIBOXEDLAYOUT: 'traditional'
      PIHOLE_DNS_: '10.5.11.2#5054;9.9.9.9'
      DNSMASQ_USER: 'pihole'
      DNSMASQ_LISTENING: 'all'
      DNSSEC: 'true'
      IPv6: 'false'
    volumes:
     - type: volume
       source: pihole_etc
       target: /etc/pihole/
     - type: volume
       source: pihole_dnsmasq
       target: /etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 9.9.9.9
    cap_add:
      - NET_ADMIN

volumes:
  pihole_etc:
  pihole_dnsmasq:

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.11.0/29
